language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
install:
  - npm i
before_script:
  - sudo apt-get install lua5.2
  - sudo apt-get install golang
  - sudo apt-get install ruby
  - sudo apt-get install ghc
script:
  - npm run build
  - npm run lint
  - npm test
  - bin/buildAll.sh
  - npm i typescript@2.6.1 -g
  - bin/checkJs.sh
  - bin/checkTs.sh
  - bin/checkLua.sh
  - bin/checkGo.sh
  - bin/checkRuby.sh
  - bin/checkBash.sh
  - bin/checkHaskell.sh
  - bin/checkPython.sh
